dags:
  persistence:
    storageClassName: local-storage
    size: 1Gi

logs:
  persistence:
    storageClassName: local-storage
    size: 1Gi

workers:
  persistence:
    storageClassName: local-storage
    size: 1Gi

triggerer:
  persistence:
    storageClassName: local-storage
    size: 1Gi

redis:
  persistence:
    storageClassName: local-storage
    size: 1Gi

postgresql:
  primary:
    persistence:
      storageClass: local-storage
