apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kcong
  labels:
    io.kompose.service: minio
  name: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: minio
    spec:
      containers:
      - args:
        - server
        - /data
        image: minio/minio:RELEASE.2022-03-17T06-34-49Z
        name: minio
        envFrom:
        - configMapRef:
            name: minio-config
        ports:
        - containerPort: 9000
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: minio-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: minio-claim0
        persistentVolumeClaim:
          claimName: minio-claim0
status: {}
