apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kcong
  labels:
    io.kompose.service: bpmn
  name: bpmn
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: bpmn
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: bpmn
    spec:
      containers:
      - image: cefriel/kcong-bpmn:production
        name: bpmn
        resources: {}
        volumeMounts:
        - mountPath: /process_engine/data
          name: bpmn-claim0
      restartPolicy: Always
      volumes:
      - name: bpmn-claim0
        persistentVolumeClaim:
          claimName: bpmn-claim0
status: {}
