apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kcong
  labels:
    io.kompose.service: django
  name: django
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: django
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: django
    spec:
      containers:
      - args:
        - /start
        name: django
        image: cefriel/kcong:backend_prod
        resources: {}
        envFrom:
        - configMapRef:
            name: django-config
      restartPolicy: Always
status: {}
