apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kcong
  labels:
    io.kompose.service: flower
  name: flower
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: flower
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: flower
    spec:
      containers:
      - args:
        - /start-flower

        name: flower
        image: cefriel/kcong:backend_prod
        envFrom:
        - configMapRef:
            name: django-config
        ports:
        - containerPort: 5555
        resources: {}
      restartPolicy: Always
status: {}
